add: table-datatable-jquery
zuramai/mazer pull request #32
Opened 2021-09-20 04:13 UTC by mrzf833

2021-09-25 04:58 UTC, zuramai commented
Can you fix the conflicts?

2021-10-01 08:11 UTC, mrzf833 commented
yeah, conflict is fixed

2021-10-01 10:31 UTC, zuramai commented
Can you combine the Datatable menu so it would be like this?
- Datatables
      - Datatable
      - Datatable (jQuery)

2021-10-01 10:36 UTC, zuramai requested changes
Change the Datatable jQuery menu to submenu

2021-10-01 10:36 UTC, zuramai commented on src/sidebar-items.json
> +  },
Change this to be a submenu

2021-10-01 13:09 UTC, mrzf833 commented on src/sidebar-items.json
> +  },
finished combine menu datatable

2021-10-02 07:11 UTC, zuramai approved these changes

2021-10-02 14:06 UTC, merged

2021-10-02 14:06 UTC, zuramai commented
Great pull request! Thanks